name: Keep Streamlit Awake

# Chạy theo lịch cron: mỗi 15 phút
on:
  schedule:
    - cron: '*/15 * * * *'  

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          echo "Pinging Streamlit app..."
          curl -fsS https://YOUR-APP-NAME.streamlit.app/ || echo "Ping failed but continue"
