name: Keep Streamlit Awake

on:
  schedule:
    - cron: '*/15 * * * *'    # mỗi 15 phút theo UTC
  workflow_dispatch:         # cho phép chạy thủ công

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          echo "Pinging Streamlit app (follow redirect)…"
          curl -fsSL https://share.streamlit.io/thumhttt/blank-app/main/streamlit_app.py \
            > /dev/null \
            || echo "Ping failed but continue"
